name: pcbtest
version: "1"
summary: pcbtest is Rally + Tempest + refstack tests
description: |
  Snap for running tests for Openstack platform using Rally framework, Tempest verifier and tests from refstack.
base: core18
grade: stable
confinement: strict

architectures: [amd64]

environment:
  PATH: $SNAP/bin:$SNAP/usr/bin:$PATH
  PYTHONPATH: $SNAP/lib/python3.6/site-packages:$SNAP/bin/rally
  PYTHONHOME: $SNAP/usr
  SNAP_SHM_PREFIX: "snap.${SNAP_NAME}."
apps:
  pcbtest:
    command: /bin/echo -e "Usage -\n 0) source novarc\n 1) pcbtest.rallyinit\n 2) pcbtest.tempestinit\n 3) pcbtest.rally verify start"
    plugs: [home, network]
  rally:
    command: rally
    plugs: [home, network]
  rallyinit:
    command: bin/rallyinit.sh
    plugs: [home, network]
  tempestinit:
    command: bin/tempestinit.sh
    plugs: [home, network]

parts:
  rally-openstack:
    plugin: python
    python-version: python3
    build-packages: [python3, python3-pip, build-essential, libffi-dev, libpq-dev, libssl-dev, libxml2-dev, libxslt1-dev, python3-dev, iputils-ping, zlib1g, libcomerr2, libgcc1]
    source: https://github.com/openstack/rally-openstack
    source-branch: master
    source-type: git
    stage-packages:
      - git
    requirements: [requirements.txt]
    constraints: [upper-constraints.txt]
  copy-parts:
    after: [rally-openstack]
    plugin: dump
    source: ./
    organize:
            rallyinit.sh: bin/rallyinit.sh
            tempestinit.sh: bin/tempestinit.sh
    stage:
            - bin/*
            - 2018.02-test-list.txt
  libc-shm-shim:
      plugin: nil
      override-build: |
          snap download libc-shm-shim --beta
          unsquashfs -f -d ${SNAPCRAFT_PART_INSTALL} libc-shm-shim_*.snap
      build-packages:
          - squashfs-tools
      stage:
          - -meta
          - -snap
  tempest:
    after: [rally-openstack]
    plugin: python
    source: https://opendev.org/openstack/tempest
    source-type: git
    requirements: [requirements.txt]
    filesets:
      exclude-conflicting-files:
        - -lib/python3.6/site-packages/importlib_metadata/__init__.py
        - -lib/python3.6/site-packages/importlib_metadata/_compat.py
        - -lib/python3.6/site-packages/importlib_metadata/docs/changelog.rst
        - -lib/python3.6/site-packages/importlib_metadata/docs/using.rst
        - -lib/python3.6/site-packages/importlib_metadata/tests/fixtures.py
        - -lib/python3.6/site-packages/importlib_metadata/tests/test_main.py
        - -lib/python3.6/site-packages/importlib_metadata/tests/test_zip.py
      include-all:
        - ./*
    stage:
      - $include-all
      - $exclude-conflicting-files
    # rally expects tempest source with .git present
    # which means we have to clone the repo into the
    # target directory, including the hidden dir
    override-prime: |
      snapcraftctl prime
      rm -fr $SNAPCRAFT_PRIME/tempest
      git clone $SNAPCRAFT_PART_SRC $SNAPCRAFT_PRIME/tempest